In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df_c = pd.read_csv('final_feature1.csv')
df_c = df_c[['Variable Label','Risk','Score']]
df_code = pd.read_excel('SDOH_2020_Codebook.xlsx', sheet_name = 'All SDOH Variables')
df_code = df_code[['Variable Name','Variable Label','Topic','Domain']]
df_code.head()

,Variable Name,Variable Label,Topic,Domain
0,ACS_AVG_HH_SIZE,Average household size,Demographics,1. Social context
1,ACS_GINI_INDEX,Gini index of income inequality,Income,2. Economic context
2,ACS_MDN_GRNDPRNT_INC,Median income of grandparent householder and/o...,Income,2. Economic context
3,ACS_MDN_GRNDPRNT_NO_PRNT_INC,Median income of grandparent householder and/o...,Income,2. Economic context
4,ACS_MDN_OWNER_COST_MORTGAGE,Median selected monthly owner costs for houses...,Housing,4. Physical infrastructure

In [3]:
df_c

,Variable Label,Risk,Score
0,Percentage of Local Education Authorities in a...,Educational Challenges,-1
1,Total number of hospitals with alcohol and/or ...,Social Environmental Risk,-1
2,Age-adjusted prevalence of adults aged 18 year...,Lifestyle,1
3,Total number of deaths from transport accident...,Transportation Risk,1
4,Percentage of households with a tablet or othe...,Technology Access Risk,1
...,...,...,...
405,Total number of short-term general hospital be...,healthcare access risk,-1
406,Total number of hospitals with alcohol and/or ...,healthcare access risk,-1
407,Total number of hospitals with obstetric care ...,healthcare access risk,-1
408,Total number of hospitals with rehabilitative ...,healthcare access risk,-1
409,Total number of hospitals with medical-surgica...,healthcare access risk,-1

In [4]:
df33 = pd.merge(df_code, df_c, on='Variable Label', how='inner')
df33

,Variable Name,Variable Label,Topic,Domain,Risk,Score
0,ACS_GINI_INDEX,Gini index of income inequality,Income,2. Economic context,financial Risk,1
1,ACS_MDN_GRNDPRNT_INC,Median income of grandparent householder and/o...,Income,2. Economic context,financial Risk,-1
2,ACS_MDN_GRNDPRNT_NO_PRNT_INC,Median income of grandparent householder and/o...,Income,2. Economic context,financial Risk,-1
3,ACS_MDN_OWNER_COST_MORTGAGE,Median selected monthly owner costs for houses...,Housing,4. Physical infrastructure,Housing Challenges,1
4,ACS_MDN_OWNER_COST_NO_MORTG,Median selected monthly owner costs for houses...,Housing,4. Physical infrastructure,Housing Challenges,1
...,...,...,...,...,...,...
392,POS_TOT_HOSP_PED_ICU,Total number of hospitals with pediatric ICU,Characteristics of health care facilities,5. Healthcare context,healthcare access risk,-1
393,POS_TOT_HOSP_REHAB,Total number of hospitals with rehabilitative ...,Characteristics of health care facilities,5. Healthcare context,healthcare access risk,-1
394,POS_TOT_RHC,Total number of Rural Health Clinics (RHCs),Characteristics of health care facilities,5. Healthcare context,healthcare access risk,-1
395,SAHIE_PCT_UNINSURED64,Estimated percentage of uninsured population f...,Health Insurance Status,5. Healthcare context,financial Risk,1
396,SAIPE_MEDIAN_HH_INCOME,Estimated median household income,Income,2. Economic context,financial Risk,-1

In [5]:
df_final = pd.read_csv('2020_2019_2018_merged_data.csv')

/var/folders/t3/bdhn2hj15377j15xf0l7j3lw0000gn/T/ipykernel_11292/2437240527.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv('2020_2019_2018_merged_data.csv')

In [9]:
dict2 ={
    'Label' : [],
    'Name' : [],
    'Risk' : [],
    'Score' : [],
    '1' : [],
    '2' : [],
    '3' : [],
    '4' : [],
}

In [10]:
notpos = []
for i in range(len(df33)):
    r = df33['Variable Name'].to_list()[i]
    try:
        if df33['Score'].to_list()[i] == 1:
            _, bins = pd.qcut(df_final[r], [0,0.6,0.85,1], retbins = True)
            dict2['1'].append(float(bins[0]))
            dict2['2'].append(float(bins[1]))
            dict2['3'].append(float(bins[2]))
            dict2['4'].append(float(bins[3]))
        else:
            _, bins = pd.qcut(df_final[r], [0,0.15,0.4,1], retbins = True)
            dict2['4'].append(float(bins[0]))
            dict2['3'].append(float(bins[1]))
            dict2['2'].append(float(bins[2]))
            dict2['1'].append(float(bins[3]))
        dict2['Label'].append(df33['Variable Label'].to_list()[i])
        dict2['Name'].append(r)
        dict2['Risk'].append(df33['Risk'].to_list()[i])
        dict2['Score'].append(df33['Score'].to_list()[i])
    except:
        notpos.append(i)
        print(df33['Variable Label'].to_list()[i])
        print(r)
        print(df33['Risk'].to_list()[i])
        print(df33['Score'].to_list()[i])
        print('\n\n')

Percentage of renter-occupied housing units with more than one occupant per room
ACS_PCT_1UP_RENT_1ROOM
Housing Challenges
-1



Percentage of households with other type of computer only
ACS_PCT_HH_OTHER_COMP_ONLY
Technology Access Risk
-1



Percentage of occupied housing units with bottled, tank, or LP gas
ACS_PCT_HU_BOT_TANK_LP_GAS
Housing Challenges
-1



Percentage of occupied housing units with coal or coke heating
ACS_PCT_HU_COAL
Housing Challenges
-1



Percentage of occupied housing units with fuel oil heating
ACS_PCT_HU_OIL
Housing Challenges
-1



Percentage of occupied housing units with other heating fuel
ACS_PCT_HU_OTHER
Housing Challenges
-1



Percentage of occupied housing units with solar energy
ACS_PCT_HU_SOLAR
Housing Challenges
-1



Percentage of occupied housing units with wood heating
ACS_PCT_HU_WOOD
Housing Challenges
-1



Percentage of population with direct-purchase and Medicare health insurance (between ages 35 and 64)
ACS_PCT_PRIVATE_MDCR_35_64
financial Risk
-1



Percentage of workers taking public transportation, excluding taxicab (ages 16 and over)
ACS_PCT_PUBL_TRANSIT
Transportation Risk
-1



Percentage of workers who use public transportation with < 15-minute commute time (ages 16 and over)
ACS_PCT_PUB_COMMT_15MIN
Transportation Risk
-1



Percentage of workers who use public transportation with 15- to 29-minute commute time (ages 16 and over)
ACS_PCT_PUB_COMMT_29MIN
Transportation Risk
-1



Total number of airborne infection isolation rooms in short-term, non-general, and long-term hospitals per 1,000 population
AHRF_ARBRNE_STNGLT_ISO_ROOM_RATE
healthcare access risk
-1



Total number of short-term general hospitals with airborne infection isolation rooms per 1,000 population
AHRF_ARBRNE_ST_G_ISO_HOSPS_RATE
healthcare access risk
-1



Total number of airborne infection isolation rooms in short-term general hospitals per 1,000 population
AHRF_ARBRNE_ST_G_ISO_ROOMS_RATE
healthcare access risk
-1



Total number of short-term general hospitals with cardiac intensive care per 1,000 population
AHRF_CARDIAC_IC_HOSP_RATE
healthcare access risk
-1



Total number of community health centers, grantees only, per 1,000 population
AHRF_COM_HEALTH_GRANT_RATE
healthcare access risk
-1



Total number of Medicare/Medicaid dual eligible beneficiaries
AHRF_DUAL_ELIG
financial Risk
-1



Total number of hospitals per 1,000 population
AHRF_HOSPS_RATE
healthcare access risk
-1



Total number of hospitals with mobile health services per 1,000 population
AHRF_HOSP_MOBILE_RATE
Transportation Risk
-1



Health Professional Shortage Area (HPSA) code-shortage of dentists
AHRF_HPSA_DENTIST
healthcare access risk
1



Health Professional Shortage Area (HPSA) code-shortage of primary care physicians
AHRF_HPSA_PRIM
healthcare access risk
1



Total number of long-term hospitals per 1,000 population
AHRF_LT_HOSP_RATE
healthcare access risk
-1



Total number of Medicaid eligible beneficiaries
AHRF_MEDICAID_ELIG
financial Risk
-1



Total number of female Medicaid eligible beneficiaries
AHRF_MEDICAID_FEMALE_ELIG
financial Risk
-1



Total number of male Medicaid eligible beneficiaries
AHRF_MEDICAID_MALE_ELIG
financial Risk
-1



Total number of short-term general hospitals with medical surgical intensive care per 1,000 population
AHRF_MEDSURGIC_HOSP_RATE
healthcare access risk
-1



Total number of short-term general hospitals with neonatal intensive care per 1,000 population
AHRF_NEONATALIC_HOSP_RATE
healthcare access risk
-1



Total number of operating rooms in short-term general hospitals per 1,000 population
AHRF_OPRT_ROOM_RATE
healthcare access risk
-1



Total number of short-term community hospitals per 1,000 population
AHRF_ST_COMM_HOSP_RATE
Transportation Risk
-1



Total number of short-term community hospitals per 1,000 population
AHRF_ST_COMM_HOSP_RATE
healthcare access risk
-1



Total number of short-term general hospitals per 1,000 population
AHRF_ST_G_HOSP_RATE
healthcare access risk
-1



Total number of short-term non-general hospitals per 1,000 population
AHRF_ST_N_G_HOSP_RATE
healthcare access risk
-1



Total number of airborne infection isolation rooms in short-term, non-general, and long-term hospitals
AHRF_TOT_ARBRNE_STNGLT_ISO_ROOM
healthcare access risk
-1



Total number of short-term general hospitals with airborne infection isolation rooms
AHRF_TOT_ARBRNE_ST_G_ISO_HOSPS
healthcare access risk
-1



Total number of airborne infection isolation rooms in short-term general hospitals
AHRF_TOT_ARBRNE_ST_G_ISO_ROOMS
healthcare access risk
-1



Total number of short-term general hospitals with cardiac intensive care
AHRF_TOT_CARDIAC_IC_HOSP
healthcare access risk
-1



Total number of community health centers, grantees only
AHRF_TOT_COM_HEALTH_GRANT
healthcare access risk
-1



Total number of hospitals with mobile health services
AHRF_TOT_HOSP_MOBILE
Transportation Risk
-1



Total number of short-term general hospitals with medical surgical intensive care
AHRF_TOT_MEDSURGIC_HOSP
healthcare access risk
-1



Total number of short-term general hospitals with neonatal intensive care
AHRF_TOT_NEONATALIC_HOSP
healthcare access risk
-1



Total number of operating rooms in short-term general hospitals
AHRF_TOT_OPRT_ROOM
healthcare access risk
-1



Total number of short-term non-general hospitals
AHRF_TOT_ST_N_G_HOSP
healthcare access risk
-1



Total number of designated toxic sites not under control
AHRF_TXC_SITE_NO_CNTRL
Social Environmental Risk
1



Total number of substance abuse treatment facilities with all three medication assisted treatment servicesÂ per 1,000 population
AMFAR_AMATFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering hepatitis C screening per 1,000 population
AMFAR_HCVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening per 1,000 population
AMFAR_HIVHCVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering HIV testing per 1,000 population
AMFAR_HIVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse treatment facilities offering all three medication assisted treatment services that accept Medicaid per 1,000 population
AMFAR_MEDAMATFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering hepatitis C screening and accept Medicaid per 1,000 population
AMFAR_MEDHCVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering hepatitis C screening and accept Medicaid per 1,000 population
AMFAR_MEDHCVTFAC_RATE
healthcare access risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening and accept Medicaid per 1,000 population
AMFAR_MEDHIVHCVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening and accept Medicaid per 1,000 population
AMFAR_MEDHIVHCVTFAC_RATE
healthcare access risk
-1



Total number of substance abuse facilities offering HIV testing and accept Medicaid per 1,000 population
AMFAR_MEDHIVTFAC_RATE
Social Environmental Risk
-1



Total number of substance abuse facilities offering HIV testing and accept Medicaid per 1,000 population
AMFAR_MEDHIVTFAC_RATE
healthcare access risk
-1



Percentage of people reporting drug dependence (ages 12 and over)
AMFAR_PCT_DRUGDEP_ABOVE12
Social Environmental Risk
1



Total number of substance abuse treatment facilities with all three medication assisted treatment services
AMFAR_TOT_AMATFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering hepatitis C screening
AMFAR_TOT_HCVTFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening
AMFAR_TOT_HIVHCVTFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering HIV testing
AMFAR_TOT_HIVTFAC
Social Environmental Risk
-1



Total number of substance abuse treatment facilities offering all three medication assisted treatment services that accept Medicaid
AMFAR_TOT_MEDAMATFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering hepatitis C screening and accept Medicaid
AMFAR_TOT_MEDHCVTFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening and accept Medicaid
AMFAR_TOT_MEDHIVHCVTFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering both HIV test and hepatitis C screening and accept Medicaid
AMFAR_TOT_MEDHIVHCVTFAC
healthcare access risk
-1



Total number of substance abuse facilities offering HIV testing and accept Medicaid
AMFAR_TOT_MEDHIVTFAC
Social Environmental Risk
-1



Total number of substance abuse facilities offering HIV testing and accept Medicaid
AMFAR_TOT_MEDHIVTFAC
healthcare access risk
-1



Total number of community food services per 1,000 people
CCBP_CFS_RATE
Food Security
-1



Total number of community housing services per 1,000 people
CCBP_CHS_RATE
Housing Challenges
-1



Total number of community food services
CCBP_TOT_CFS
Food Security
-1



Total number of community housing services
CCBP_TOT_CHS
Housing Challenges
-1



Total number of fitness centers and recreational sports centers
CCBP_TOT_FCRSC
Lifestyle
-1



Total number of specialized food stores
CCBP_TOT_SFS
Food Security
-1



Total number of supermarkets and other grocery (except convenience) stores
CCBP_TOT_SOGS
Food Security
-1



Total number of people living with diagnosed HIV at the end of the year per 100,000, American Indian and Alaska Native (ages 13 and over)
CDCAP_HIVDIAG_AIAN_RATE_ABOVE13
Disease Risk
1



Percentage of adults reporting no leisure-time physical activity (ages 20 and over)
CHR_PCT_PHYS_INACTIVITY
Lifestyle
1



Percentage of Local Education Authorities in a county that offer early childhood services to children (ages 0-2)
CRDC_PCT_COUNTY_ECE
Educational Challenges
-1



Total number of alternative schools in the county
CRDC_TOT_ALT
Educational Challenges
-1



Total number of special education schools in the county
CRDC_TOT_SPEDS
Educational Challenges
-1



Primary Rural-Urban Commuting Area Code 2000
ERS_RUCA1_2000
Transportation Risk
0



Primary Rural-Urban Commuting Area Code 2010  (ZIP level)
ERS_RUCA1_2010
Transportation Risk
0



Secondary Rural-Urban Commuting Area Code 2000
ERS_RUCA2_2000
Transportation Risk
0



Secondary Rural-Urban Commuting Area Code 2010 (ZIP level)
ERS_RUCA2_2010
Transportation Risk
0



Percentage of tract population who are Native Hawaiian or Other Pacific Islander living more than 1 mile from the nearest supermarket, supercenter, or large grocery store
FARA_PCT_LA_1_NHPI
Food Security
1



Indicator for low income and low access tract measured at 1 mile for urban areas and 20 miles for rural areas
FARA_TRACT_LILA_1_20
financial Risk
0



Indicator for low income and low access tract using vehicle access or low income and low access tract measured at 20 miles
FARA_TRACT_LILA_VEHICLE_20
Transportation Risk
0



Indicator for low income and low access tract using vehicle access or low income and low access tract measured at 20 miles
FARA_TRACT_LILA_VEHICLE_20
financial Risk
0



Percentage of all farmers' markets that accept SFMNP benefits
FEA_PCT_FARMERS_MARKET_SFMNP
Food Security
-1



Percentage of all farmers' markets that accept SNAP benefits
FEA_PCT_FARMERS_MARKET_SNAP
Food Security
-1



Total number of the Food Distribution Program on Indian Reservations (FDPIR) sites
FEA_TOT_FDPIR
Food Security
-1



Total number of food banks (from Feeding America's nationwide network of food banks)
FEA_TOT_FOODBANK
Food Security
-1



Percentage of home health agencies offering medical social services
HHC_PCT_HHA_MEDICAL
healthcare access risk
-1



Percentage of home health agencies offering speech pathology services
HHC_PCT_HHA_SPEECH
healthcare access risk
-1



Medically Underserved Areas (MUAs) - County
HRSA_MUA_COUNTY
healthcare access risk
1



Total number of Indian Health Service health care facilities
IHS_HEALTH_FACILITY
healthcare access risk
-1



Total number of Indian Health Service health care facilities per 1,000 population
IHS_HEALTH_FACILITY_RATE
healthcare access risk
-1



Percentage of days with PM2.5 levels over the national ambient air quality standard (modeled estimates only)
NEPHTN_PCT_MODPD_PM25
Climate Risk
1



Percentage of days with PM2.5 levels over the national ambient air quality standard (monitored values only)
NEPHTN_PCT_MONPD_PM25
Climate Risk
1



Total number of deaths directly caused by storm events during the year
NOAAS_TOT_DEATHS_DIRECT
Climate Risk
1



Total number of deaths indirectly caused by storm events during the year
NOAAS_TOT_DEATHS_INDIRECT
Climate Risk
1



Total number of heat events
NOAAS_TOT_HEAT_EVENTS
Climate Risk
1



Total number of injuries directly caused by storm events during the year
NOAAS_TOT_INJURIES_DIRECT
Climate Risk
1



Total number of injuries indirectly caused by storm events during the year
NOAAS_TOT_INJURIES_INDIRECT
Climate Risk
1



Total number of wildfires
NOAAS_TOT_WILDFIRE
Climate Risk
1



Total number of Community Mental Health Centers per 1,000 population
POS_CMHC_RATE
Social Environmental Risk
-1



Total number of Federally Qualified Health Centers (FQHCs) per 1,000 population
POS_FQHC_RATE
healthcare access risk
-1



Total number of hospitals with alcohol and/or drug abuse inpatient care per 1,000 population
POS_HOSP_ALC_RATE
Social Environmental Risk
-1



Total number of hospitals with alcohol and/or drug abuse inpatient care per 1,000 population
POS_HOSP_ALC_RATE
healthcare access risk
-1



Total number of hospitals with ambulance servicesÂ per 1,000 population
POS_HOSP_AMBULANCE_RATE
Transportation Risk
-1



Total number of hospitals with emergency department per 1,000 population
POS_HOSP_ED_RATE
healthcare access risk
-1



Total number of hospitals with medical-surgical ICU per 1,000 population
POS_HOSP_MEDSURG_ICU_RATE
healthcare access risk
-1



Total number of hospitals with obstetric care per 1,000 population
POS_HOSP_OBSTETRIC_RATE
healthcare access risk
-1



Total number of hospitals with pediatric ICU per 1,000 population
POS_HOSP_PED_ICU_RATE
healthcare access risk
-1



Percentage of hospitals that are government (federal, state, local, district) hospitals
POS_PCT_HOSP_GOV
healthcare access risk
-1



Total number of Rural Health Clinics (RHCs) per 1,000 population
POS_RHC_RATE
healthcare access risk
-1



Total number of Community Mental Health Centers
POS_TOT_CMHC
Social Environmental Risk
-1



Total number of hospitals with alcohol and/or drug abuse inpatient care
POS_TOT_HOSP_ALC
Social Environmental Risk
-1



Total number of hospitals with alcohol and/or drug abuse inpatient care
POS_TOT_HOSP_ALC
healthcare access risk
-1



Total number of hospitals with ambulance services
POS_TOT_HOSP_AMBULANCE
Transportation Risk
-1



Total number of hospitals with pediatric ICU
POS_TOT_HOSP_PED_ICU
healthcare access risk
-1



Total number of hospitals with rehabilitative care
POS_TOT_HOSP_REHAB
healthcare access risk
-1



Total number of Rural Health Clinics (RHCs)
POS_TOT_RHC
healthcare access risk
-1

In [11]:
len(notpos)

121

In [12]:
pd.DataFrame(dict2)

,Label,Name,Risk,Score,1,2,3,4
0,Gini index of income inequality,ACS_GINI_INDEX,financial Risk,1,0.01,0.43,0.49,0.89
1,Median income of grandparent householder and/o...,ACS_MDN_GRNDPRNT_INC,financial Risk,-1,250001.00,56357.00,39063.00,2499.00
2,Median income of grandparent householder and/o...,ACS_MDN_GRNDPRNT_NO_PRNT_INC,financial Risk,-1,250001.00,41829.00,28235.00,2499.00
3,Median selected monthly owner costs for houses...,ACS_MDN_OWNER_COST_MORTGAGE,Housing Challenges,1,368.00,1525.00,2347.00,4001.00
4,Median selected monthly owner costs for houses...,ACS_MDN_OWNER_COST_NO_MORTG,Housing Challenges,1,99.00,531.00,783.00,1501.00
...,...,...,...,...,...,...,...,...
271,Total number of home health agencies,POS_TOT_HHA,healthcare access risk,-1,1548.00,6.00,2.00,0.00
272,Total number of hospitals with emergency depar...,POS_TOT_HOSP_ED,healthcare access risk,-1,121.00,3.00,1.00,0.00
273,Total number of hospitals with medical-surgica...,POS_TOT_HOSP_MEDSURG_ICU,healthcare access risk,-1,173.00,2.00,1.00,0.00
274,Estimated percentage of uninsured population f...,SAHIE_PCT_UNINSURED64,financial Risk,1,2.40,10.60,14.90,35.80
275,Estimated median household income,SAIPE_MEDIAN_HH_INCOME,financial Risk,-1,160305.00,59259.00,50235.00,22901.00

In [13]:
# notpos2 = []
# for i in notpos:
#     try:
#         df_final[name[i]].value_counts()/len(df_final)
#         notpos2.append(i)
#     except:
#         continue
# len(notpos2), len(notpos)

In [14]:
error1 = []
for e in notpos:
    r = df33['Variable Name'].to_list()[e]
    try:
        if df_final[r].mode().tolist()[0] == 0:
            lst1 = df_final[r].dropna().tolist()
            lst2 = [x for x in lst1 if x != 0]
            lst2 = np.array(lst2)
            print(np.quantile(lst2, 0.7))
            if df33['Score'].to_list()[e] == 1:
                dict2['1'].append(min(lst1))
                dict2['2'].append(float(0))
                dict2['3'].append(float(np.quantile(lst2, 0.7)))
                dict2['4'].append(max(lst1))
            else:
                dict2['1'].append(max(lst1))
                dict2['2'].append(float(np.quantile(lst2, 0.7)))
                dict2['3'].append(float(0))
                dict2['4'].append(min(lst1))
            dict2['Label'].append(df33['Variable Label'].to_list()[e])
            dict2['Name'].append(df33['Variable Name'].to_list()[e])
            dict2['Risk'].append(df33['Risk'].to_list()[e])
            dict2['Score'].append(df33['Score'].to_list()[e])
    except:
        error1.append(r)

9.13
0.64
13.35
2.01
9.78
1.8789999999999416
1.09
6.81
0.62
5.29
52.00799999999988
51.18399999999987
0.03
0.17
0.01
0.05
0.01
0.01
0.01
0.01
0.14
0.01
46.0
121.0
4.0
19.0
3.0
4.0
89.0
6.0
1.0
0.0038
0.0212
0.0185
0.0207
0.0038
0.0173
0.0173
0.0152
0.0152
0.017
0.017
3.0
13.0
13.0
15.0
3.0
11.0
10.0
10.0
11.0
11.0
400.8
40.0
10.0
7.0
0.08
1.0
1.0
1.0
61.67
55.0
1.0
1.0
2.0
0.05
2.7
3.0
1.0
6.0
6.0
14.0
5.0
0.02
0.01
0.01
0.04
0.01
6.25
0.2
4.0
7.0
7.0
1.0
3.0
6.0

In [22]:
pd.DataFrame(dict2).to_csv('threehold_variable.csv')
pd.DataFrame(dict2)

,Label,Name,Risk,Score,1,2,3,4
0,Gini index of income inequality,ACS_GINI_INDEX,financial Risk,1,0.01,0.43,0.49,0.89
1,Median income of grandparent householder and/o...,ACS_MDN_GRNDPRNT_INC,financial Risk,-1,250001.00,56357.00,39063.00,2499.00
2,Median income of grandparent householder and/o...,ACS_MDN_GRNDPRNT_NO_PRNT_INC,financial Risk,-1,250001.00,41829.00,28235.00,2499.00
3,Median selected monthly owner costs for houses...,ACS_MDN_OWNER_COST_MORTGAGE,Housing Challenges,1,368.00,1525.00,2347.00,4001.00
4,Median selected monthly owner costs for houses...,ACS_MDN_OWNER_COST_NO_MORTG,Housing Challenges,1,99.00,531.00,783.00,1501.00
...,...,...,...,...,...,...,...,...
357,Total number of hospitals with alcohol and/or ...,POS_TOT_HOSP_ALC,Social Environmental Risk,-1,41.00,7.00,0.00,0.00
358,Total number of hospitals with alcohol and/or ...,POS_TOT_HOSP_ALC,healthcare access risk,-1,41.00,7.00,0.00,0.00
359,Total number of hospitals with ambulance services,POS_TOT_HOSP_AMBULANCE,Transportation Risk,-1,2.00,1.00,0.00,0.00
360,Total number of hospitals with pediatric ICU,POS_TOT_HOSP_PED_ICU,healthcare access risk,-1,15.00,3.00,0.00,0.00
361,Total number of Rural Health Clinics (RHCs),POS_TOT_RHC,healthcare access risk,-1,74.00,6.00,0.00,0.00

In [19]:
error1

['AHRF_DUAL_ELIG',
 'AHRF_MEDICAID_ELIG',
 'AHRF_MEDICAID_FEMALE_ELIG',
 'AHRF_MEDICAID_MALE_ELIG',
 'AMFAR_PCT_DRUGDEP_ABOVE12',
 'CHR_PCT_PHYS_INACTIVITY',
 'ERS_RUCA1_2000',
 'ERS_RUCA2_2000',
 'FEA_TOT_FDPIR',
 'NEPHTN_PCT_MODPD_PM25']

In [20]:
for i in error1:
    if i in df_final.columns:
        print(True)
    else:
        print('boooooo')

boooooo
boooooo
boooooo
boooooo
boooooo
boooooo
boooooo
boooooo
boooooo
boooooo

In [21]:
df_health = pd.read_csv('healthdata_transformed.csv')
df_health

,Unnamed: 0,COUNTYFIPS,Obesity among adults aged >=18 years,Stroke among adults aged >=18 years,Arthritis among adults aged >=18 years,Mammography use among women aged 50-74 years,Depression among adults aged >=18 years,Vision disability among adults aged >=18 years,Chronic obstructive pulmonary disease among adults aged >=18 years,Visits to dentist or dental clinic among adults aged >=18 years,...,Binge drinking among adults aged >=18 years,Fair or poor self-rated health status among adults aged >=18 years,Current asthma among adults aged >=18 years,Visits to doctor for routine checkup within the past year among adults aged >=18 years,Cognitive disability among adults ages >=18 years,Hearing disability among adults aged >=18 years,Diagnosed diabetes among adults aged >=18 years,"Older adult men aged >=65 years who are up to date on a core set of clinical preventive services: Flu shot past year, PPV shot ever, Colorectal cancer screening",Physical health not good for >=14 days among adults aged >=18 years,Coronary heart disease among adults aged >=18 years
0,0,1003,38.158065,3.329032,31.293548,77.829032,22.567742,4.622581,7.996774,64.974194,...,16.025806,17.412903,9.929032,74.890323,13.387097,7.061290,12.103226,54.506452,12.422581,6.922581
1,1,1017,44.588889,4.555556,34.033333,77.277778,22.433333,7.333333,9.800000,56.566667,...,12.511111,24.644444,11.122222,79.255556,16.988889,7.488889,16.255556,37.922222,15.444444,8.033333
2,2,1029,36.700000,3.750000,32.750000,74.875000,25.475000,5.875000,10.000000,58.900000,...,14.625000,21.775000,10.550000,75.425000,16.925000,7.975000,12.950000,40.725000,14.875000,7.675000
3,3,1039,40.507143,4.185714,34.185714,74.021429,23.735714,6.578571,10.342857,56.707143,...,13.392857,23.085714,10.807143,77.371429,16.942857,8.364286,14.350000,41.478571,15.257143,8.357143
4,4,1057,37.480000,4.200000,35.000000,76.200000,24.340000,6.680000,10.760000,56.200000,...,13.860000,23.280000,10.740000,76.700000,17.360000,8.600000,14.340000,42.560000,15.600000,8.480000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,3137,56023,30.425000,2.875000,24.625000,67.450000,19.825000,4.375000,7.125000,69.875000,...,16.525000,14.600000,9.725000,65.850000,12.825000,7.500000,9.000000,33.125000,11.375000,5.800000
3138,3138,56031,37.550000,3.700000,29.200000,65.050000,19.500000,5.200000,8.750000,66.850000,...,14.550000,17.750000,9.850000,67.700000,13.000000,9.500000,11.700000,41.700000,13.150000,7.550000
3139,3139,56039,21.875000,1.950000,19.075000,74.500000,17.850000,2.925000,4.350000,76.775000,...,21.075000,9.650000,8.750000,65.300000,9.500000,5.450000,6.275000,41.875000,7.925000,3.925000
3140,3140,56017,33.350000,3.950000,31.400000,64.150000,21.050000,5.450000,9.350000,62.850000,...,13.850000,17.600000,9.900000,67.850000,13.350000,10.200000,12.100000,41.450000,13.650000,8.200000
3141,3141,56027,35.300000,4.100000,28.600000,64.100000,22.200000,6.500000,10.500000,58.700000,...,13.700000,20.000000,11.000000,66.300000,15.800000,10.200000,12.200000,38.800000,14.700000,8.200000

In [40]:
df_health = df_health.iloc[:,2:]

In [41]:
# np.quantile(lst2, 0.7)
er = []
lsth = df_health.columns
for i in lsth:
    e = df_health[i].dropna().to_numpy()
    er.append(np.quantile(e, 0.7))

In [42]:
dict1 = {
    'diseases' : df_health.columns,
    'breakpoint' :er,
}

In [44]:
pd.DataFrame(dict1).to_csv('health_thresholds.csv')

In [52]:
df_life = pd.read_csv('life_final.csv')
df_life

,Unnamed: 0,TRACTFIPS,nq(x) AT Under 1,nq(x) AT 1 to 4,nq(x) AT 5 to 14,nq(x) AT 15 to 24,nq(x) AT 25 to 34,nq(x) AT 35 to 44,nq(x) AT 45 to 54,nq(x) AT 55 to 64,...,se(e(x)) AT 1 to 4,se(e(x)) AT 5 to 14,se(e(x)) AT 15 to 24,se(e(x)) AT 25 to 34,se(e(x)) AT 35 to 44,se(e(x)) AT 45 to 54,se(e(x)) AT 55 to 64,se(e(x)) AT 65 to 74,se(e(x)) AT 75 to 84,se(e(x)) AT 85 and older
0,0,1001020100,0.019736,0.008884,0.006180,0.008613,0.023923,0.020311,0.017889,0.084746,...,1.5617,1.4302,1.3790,1.3889,1.2441,1.1790,1.1612,1.1630,1.1217,1.4998
1,1,1001020200,0.008647,0.009001,0.001430,0.004869,0.010390,0.026667,0.061996,0.133411,...,3.0841,3.0314,3.0356,3.0368,3.0462,3.0873,3.2094,3.5736,4.5695,6.0754
2,2,1001020400,0.004260,0.001026,0.002392,0.002786,0.012019,0.025924,0.057895,0.113929,...,0.9709,0.9717,0.9607,0.9503,0.9008,0.8452,0.7922,0.6928,0.6618,0.8547
3,3,1001020500,0.004949,0.001067,0.001028,0.004714,0.007774,0.006899,0.036202,0.079661,...,1.1682,1.1665,1.1655,1.1617,1.1617,1.1636,1.1848,1.2279,1.3614,1.8379
4,4,1001020600,0.015812,0.001050,0.001357,0.018496,0.016841,0.037500,0.040924,0.121820,...,1.4327,1.4341,1.4360,1.3873,1.3583,1.3057,1.3133,1.3652,1.5426,2.2593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67143,18385,56043000200,0.017272,0.004510,0.000932,0.007036,0.035273,0.004248,0.029949,0.056913,...,2.2360,2.2172,2.2192,2.2338,2.1604,2.1612,2.1994,2.2952,2.4212,3.3954
67144,18386,56043000301,0.004286,0.000907,0.000997,0.015256,0.014722,0.033557,0.070423,0.053476,...,2.7929,2.7954,2.7982,2.7563,2.7697,2.7530,2.8391,2.9623,3.4056,4.3560
67145,18387,56043000302,0.004802,0.000728,0.000871,0.009443,0.025575,0.005195,0.022462,0.067470,...,2.0863,2.0877,2.0895,2.0648,1.9370,1.9328,1.9416,1.9998,2.1688,2.8395
67146,18388,56045951100,0.004551,0.000904,0.001167,0.007956,0.012685,0.016725,0.035639,0.073386,...,1.0717,1.0725,1.0736,1.0793,1.0904,1.1054,1.1423,1.2175,1.3980,2.0069
67147,18389,56045951300,0.004551,0.000904,0.003237,0.011881,0.012422,0.046647,0.028056,0.088569,...,1.6158,1.6172,1.6066,1.5686,1.5555,1.4415,1.4348,1.4890,1.5970,2.1919

In [53]:
tq = []
for i in df_life.columns:
    if 'e(x) AT' in i:
        print(i)
        tq.append(i)

e(x) AT Under 1
e(x) AT 1 to 4
e(x) AT 5 to 14
e(x) AT 15 to 24
e(x) AT 25 to 34
e(x) AT 35 to 44
e(x) AT 45 to 54
e(x) AT 55 to 64
e(x) AT 65 to 74
e(x) AT 75 to 84
e(x) AT 85 and older

In [54]:
df_life[tq]

,e(x) AT Under 1,e(x) AT 1 to 4,e(x) AT 5 to 14,e(x) AT 15 to 24,e(x) AT 25 to 34,e(x) AT 35 to 44,e(x) AT 45 to 54,e(x) AT 55 to 64,e(x) AT 65 to 74,e(x) AT 75 to 84,e(x) AT 85 and older
0,73.1,73.5,70.2,60.6,51.1,42.2,33.0,23.5,15.2,8.2,1.4
1,76.9,76.5,73.2,63.3,53.6,44.1,35.2,27.2,20.6,16.9,11.6
2,75.4,74.7,70.8,61.0,51.1,41.7,32.7,24.4,16.9,9.8,2.1
3,79.4,78.8,74.9,65.0,55.2,45.6,35.9,27.1,19.0,12.1,6.1
4,73.1,73.3,69.4,59.5,50.5,41.3,32.7,23.9,16.5,8.8,3.3
...,...,...,...,...,...,...,...,...,...,...,...
67143,80.1,80.5,76.8,66.9,57.3,49.2,39.4,30.5,22.0,13.1,7.2
67144,79.9,79.2,75.3,65.3,56.3,47.0,38.5,31.0,22.5,16.2,9.8
67145,81.8,81.2,77.3,67.3,57.9,49.3,39.6,30.4,22.2,14.6,8.9
67146,79.0,78.3,74.4,64.5,55.0,45.6,36.3,27.4,19.2,12.0,6.5
67147,78.6,78.0,74.1,64.3,55.0,45.6,37.6,28.6,20.9,13.3,9.5

In [55]:
# np.quantile(lst2, 0.7)
high = []
low = []
for i in tq:
    e = df_life[i].dropna().to_numpy()
    high.append(np.quantile(e, 0.7))
    low.append(np.quantile(e, 0.3))

In [57]:
dict3 = {
    'range' : tq,
    'high' : high,
    'low' : low
}
pd.DataFrame(dict3).to_csv('life_threshold.csv')

In [76]:
df_final2 = pd.read_csv('2020_2019_2018_merged_data.csv')
df_final2.columns

/var/folders/t3/bdhn2hj15377j15xf0l7j3lw0000gn/T/ipykernel_4022/1011447948.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final2 = pd.read_csv('2020_2019_2018_merged_data.csv')

Index(['Unnamed: 0', 'YEAR', 'TRACTFIPS', 'COUNTYFIPS', 'STATEFIPS', 'STATE',
       'COUNTY', 'REGION', 'TERRITORY', 'ACS_TOT_POP_WT',
       ...
       'SEDA_CS_MN_MATH_GR8_NEC', 'SEDA_CS_TOT_MATH_GR3_NEC',
       'SEDA_CS_TOT_MATH_GR8_NEC', 'SEDA_CS_MN_ELA_GR3_NEC',
       'SEDA_CS_MN_ELA_GR8_NEC', 'SEDA_CS_TOT_ELA_GR3_NEC',
       'SEDA_CS_TOT_ELA_GR8_NEC', 'LTC_TOT_RESIDENTS',
       'LTC_TOT_RESIDENTS_RATE', 'LTC_AVG_DAILY_CENSUS'],
      dtype='object', length=1222)

In [67]:
df_final2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 1222 entries, Unnamed: 0 to LTC_AVG_DAILY_CENSUS
dtypes: float64(1206), int64(11), object(5)
memory usage: 9.7+ KB

In [69]:
# with open('2020_2019_2018_merged_data.csv', 'r') as file:
#     for line in file:
#         print(line)

In [75]:
import csv

# Open CSV file using csv.reader
with open('2020_2019_2018_merged_data.csv', 'r') as file:
    t = list(csv.reader(file))

# Get the number of rows
num_rows = len(t)

print("Number of rows:", num_rows)

Number of rows: 140593